version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      linting-formatting:
        patterns:
          - "@biomejs/biome"
      testing:
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"
      build-tools:
        patterns:
          - "vite"
          - "@lokalise/package-vite-config"
      typescript:
        patterns:
          - "typescript"
          - "@types/node"